### ISSUE TITLE
ci: Evaluate testing for Opera browser

### ISSUE THREAD

**Issue by danielptv** [danielptv/bookmark-bar-switcher#150]
Right now the automated tests only cover Chrome. Since Opera will now be officially supported too it should be covered by the tests.

However, it seems like Opera does not support `headless` mode. Additionally a solution needs to be found for integrating Opera into the E2E testing tool, i.e. the currently used *Puppeteer*. It may be worth thinking about changing to a different E2E testing solution like [Playwright](https://github.com/microsoft/playwright).

**Comment by Kamiikaze** [comment]
I already started to implement a test and it passes. But I'm not rly satisfied how I can test it. Also since the implementation mentioned in #104 changed the functionality, this is not useable now. But maybe it gives you a hint how we can implement a test for opera, as there aren't any E2E testing tools for Opera afaik.

`popup.test.js`
```ts
    test('Switch bookmark bars by Workspace change', async () => {
        const linkedWorkspaces: SyncedWorkspaceEntry[] = [
            { workspaceId: '0', workspaceName: 'Default', syncedBarTitle: 'DefaultBar' },
            { workspaceId: '1', workspaceName: 'Gaming', syncedBarTitle: '' },
            { workspaceId: '2', workspaceName: 'Coding', syncedBarTitle: 'CodingBar' },
        ];
        const definedBarTitles = ['DefaultBar', 'CodingBar', 'GamingBar', 'MiscBar'];

        const extensionUrl = getExtensionURL(browser);
        await page.goto(extensionUrl, { waitUntil: ['domcontentloaded', 'networkidle2'] });
        const customDirId = await getDirectoryId(page, CUSTOM_BARS_DIR);

        for (const barTitle of definedBarTitles) {
            if (barTitle !== '') {
                const dirId = await createDirectory(page, { title: barTitle }, customDirId);
                await createBookmarks(page, [{ title: `${barTitle}-Bookmark`, url: 'https://www.google.com' }], dirId);
            }
        }

        await page.reload();

        const countBars = await page.$$eval('div', (divs) => {
            return divs.filter((div) => div.classList.contains('dndrop-draggable-wrapper'));
        });

        expect(countBars).toHaveLength(definedBarTitles.length + 1);

        // Open new tabs and check if the correct bar is displayed
        for (let i = 0; i < definedBarTitles.length + 1; i++) {
            const tab = await openNewTab(browser);
            await tab.goto(extensionUrl, { waitUntil: ['domcontentloaded', 'networkidle2'] });

            const randomWorkspaceId = Math.floor(Math.random() * definedBarTitles.length).toString();
            const workspace = linkedWorkspaces.find((ws) => ws.workspaceId === randomWorkspaceId);
            if (!workspace || workspace.syncedBarTitle === '') {
                return;
            }
            const barId = await getDirectoryId(tab, workspace.syncedBarTitle);
            const barTitles = await getBookmarkTitles(tab, barId);
            console.log(barTitles);

            expect(barTitles[0]).toBe(`${workspace.syncedBarTitle}-Bookmark`);
        }
    });
```

`helpers.ts`
```ts
export async function openNewTab(browser: Browser): Promise<Page> {
    const pagePromise = new Promise<Page | null>((resolve) =>
        browser.once('targetcreated', (target) => resolve(target.page())),
    );
    await browser.newPage();
    return (await pagePromise)!;
}
```

**Comment by Kamiikaze** [comment]
> As far as tests for the workspaces feature go, I did not manage to find a way to programmatically switch between workspaces, not even by means of keyboard shortcuts. Therefore, I will leave this out for now as anything else would be a rather hacky solution.
> 
> At a later point in time we may consider covering this functionality with unit tests.

There are shortcuts for it. But at default they aren't bound. Just go to **opera://settings/keyboardShortcuts** and search for **Switch to**

![Opera Shortcuts Workspace](https://i.imgur.com/dSwRU4S.png)

**Comment by danielptv** [comment]
Yeah I found this and set it through a preferences file. However, Puppeteer for some reason isn't able to switch it using that shortcut (it does work when I switch it manually with the shortcut within the browser Puppeteer is using).
