### ISSUE TITLE
Lost bookmarks. 

### ISSUE THREAD

**Issue by Zanatoo** [danielptv/bookmark-bar-switcher#22]
I came across this extension on the chrome web store. Upon installing I was impressed. It seemed to do exactly what I was looking for. I created an 'Original' bar and then a 'Work' bar and proceeded to move all my work related BM's to the new Work bar. 

Then, I decided to log in remotely to my home PC to see if it all synced, it didn't, though it had removed my work BM's that I had moved to the new bar.

Upon going back to my work PC, it had lost both the new BM bar I had created along with all my work BM's that I had just moved to the new BM bar. Hundreds of bookmarks lost. GRRRR!!!  

When I go to 'Other Bookmarks' (on the far right of the BM bar) it now contains hundreds of empty folders called Bookmarks Bars and I seem to have lost the ability to create new bars.

**Comment by Zanatoo** [comment]
It created 12822 empty 'Bookmark bars' folders which pretty much froze up Chrome when opening the bookmarks manager. I finally got it to open fully and it's deleting them now at a rate of one about every 5 seconds. 

I wouldn't have had anything like that many bookmarks, a couple of hundred at the most.

**Comment by danielptv** [comment]
Sorry for the late response. 

I came across this issue myself when testing the application and had fixed it in 1.3.1. Unfortunately, Google had trouble publishing the updated version (issues with requested bookmarks and storage permissions for some reason). The now published version 1.3.2 should not contain the mentioned bug any longer.

My apologies.
