### ISSUE TITLE
Bookmarks getting mixed together

### ISSUE THREAD

**Issue by Kamiikaze** [danielptv/bookmark-bar-switcher#3]
I came to the issue, where when switching the Bars with "CTRL+ArrowKey" to quickly, the bars getting mixed/merged together.
Currently still on v0.1 cuz your update isn't available in the chrome store yet.

I am using Opera. Will try to replicate this issue again on Opera when I got time to and also in Chrome.

**Comment by danielptv** [comment]
I have tried to replicate the issue using the 1.0.0 version in Chrome but wasn't able to. Once the 1.0.0 version has been approved in the Chrome Web Store please try to replicate again on your end.

**Comment by danielptv** [comment]
Update: I was able to reproduce and identify the problem. When you hold down the keyboard shortcut MAX_WRITE_OPERATIONS_PER_MINUTE quota (chrome.storage) is quickly exceeded. This in turn leads to the bookmark bars geting merged as you have described.

I have fixed this issue by limiting the number of shortcuts to 50/ms. 
While this fixes the issue there is one downside to my solution: You cannot hold down the key as you used to before. Instead you have to actually press the shortcut multiple times to move up/down the list of bookmark bars.

**Comment by Kamiikaze** [comment]
I haven't hold down the key, I just quickly pressed the arrow keys twice. But yea, limiting the # of inputs / sec will be a good solution. Thanks! :)
