### ISSUE TITLE
Deleting Bars

### ISSUE THREAD

**Issue by Kamiikaze** [danielptv/bookmark-bar-switcher#4]
Thanks for keep updating the extension!

I run into the issue when editing a Bar. I accidentally clicked twice on "Edit" so my bar go instantly deleted. Would be good to add a confirmation dialog to it.

Also after deleting this bar, when switching to another, the current bar with the selected one will be merged. (I deleted the current active one, so the folder was empty)

I am not sure if the delete action is necessary because this will also delete all Bookmarks inside the bar.

**Comment by danielptv** [comment]
Good points, I will look into it. The merging is an oversight on my part, should be an easy fix.
Probably I will add a confirmation to the delete button or move it somewhere else in the UI.

**Comment by Kamiikaze** [comment]
My Opera Browser also have a section of "Trashed Bookmarks". Maybe you can move all the bookmarks from the deleted bar to it.
Didn't saw something similar for Chrome.
But would be good if the bookmarks didn't get deleted instantly.
