### ISSUE TITLE
Bookmark-Bars getting merged by wrong "active" Bar

### ISSUE THREAD

**Issue by Kamiikaze** [danielptv/bookmark-bar-switcher#68]
**Issue:**
Having an Issue, where the active BMB isn't saved correctly. Happend second time now.
The active bar wasn't the one which bookmarks are loaded.
So by clicking the one which is marked as active the BMB disappears and the bookmarks getting merged with the wrong folder.

**How to reproduce:**
Not sure in which way it is reproducible.

**Possible solution:**
Maybe you can add a function, which checks if the folder of the selected/active BMB is empty, to prevent items getting merged in another folder.
If the folder isnt empty, promt a confirmation dialog or smth like this.
Also a "fix"-function could be useful for this scenario where it checks which custom BMB folder is empty (because this should be the active BMB) and compare this with the active one (in the local storage sync). If its odd, prompt user if he want to set the correct active BMB.

Hope it can help you with this issue. 🙂

**Comment by Kamiikaze** [comment]
Okay, after testing this with my "real" Bookmarks i faced this issue again.
Because I have so many bookmarks, the limit exceeds to fast. That's why the bookmarks didn't get moved and merged.
![image](https://github.com/danielptv/bookmark-bar-switcher/assets/13954000/d26440d3-b6f1-4ec2-abd4-d2ab6ae8280a)

https://developer.chrome.com/docs/extensions/reference/storage/#property-sync

> MAX_WRITE_OPERATIONS_PER_MINUTE
> 120

**Comment by danielptv** [comment]
Thank you for analyzing. 
As there doesn't seem to be a way to increase the limits the only option is to reduce the number of write operations. I need to have a look whether it is possible to copy entire directories rather than each individual bookmark (and if that would result in one write operation only!).

**Comment by Kamiikaze** [comment]
Yea, that would be great.
If not, we maybe need to count the Bookmarks and check the limit before moving them to prevent accidentally merges.

**Comment by danielptv** [comment]
I have figured out the cause of the problem. It aren't in fact the operations on the bookmarks API but rather the too excessive usage of chrome.storage.sync which is limited to 120 write operations per minute.
I have greatly reduced the usage of storage so the issue should hopefully no longer persist.

I will merge when I have finished testing.

**Comment by Kamiikaze** [comment]
Awesome! Thanks 🙂
